<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class GenerateBrandingCSS extends Command
{
    protected $signature = 'branding:generate';

    protected $description = 'Generate branding CSS file from configuration';

    public function handle(): int
    {
        $cssPath = public_path('css/brand.css');
        $config = config('branding');

        $this->info('Generating branding CSS...');

        // Ensure directory exists
        $dir = dirname($cssPath);
        if (! File::isDirectory($dir)) {
            File::makeDirectory($dir, 0755, true);
            $this->info("Created directory: {$dir}");
        }

        $css = $this->buildCSSContent($config);

        // Write CSS file
        if (File::put($cssPath, $css)) {
            $this->info("✓ Branding CSS generated successfully!");
            $this->info("  Location: {$cssPath}");
            $this->info("  Size: " . number_format(strlen($css)) . " bytes");
            return self::SUCCESS;
        }

        $this->error("Failed to write CSS file to: {$cssPath}");
        $this->error("Please check directory permissions.");
        return self::FAILURE;
    }

    /**
     * Build CSS content from configuration
     */
    protected function buildCSSContent(array $config): string
    {
        $colors = $config['colors'] ?? [];
        $typography = $config['typography'] ?? [];
        $design = $config['design'] ?? [];

        $css = <<<CSS
/**
 * Kre8ivDesigns Marketing - Brand Styles
 * Auto-generated from config/branding.php
 * DO NOT EDIT THIS FILE DIRECTLY - Changes will be overwritten
 */

:root {
    /* Brand Colors */
    --brand-primary: {$colors['primary']};
    --brand-primary-dark: {$colors['primary_dark']};
    --brand-primary-light: {$colors['primary_light']};
    --brand-secondary: {$colors['secondary']};
    --brand-accent: {$colors['accent']};

    /* Text Colors */
    --brand-text-primary: {$colors['text_primary']};
    --brand-text-secondary: {$colors['text_secondary']};

    /* Background Colors */
    --brand-bg: {$colors['background']};
    --brand-bg-alt: {$colors['background_alt']};

    /* Status Colors */
    --brand-success: {$colors['success']};
    --brand-warning: {$colors['warning']};
    --brand-danger: {$colors['danger']};
    --brand-info: {$colors['info']};

    /* Typography */
    --brand-font-primary: {$typography['font_primary']};
    --brand-font-secondary: {$typography['font_secondary']};
    --brand-font-mono: {$typography['font_mono']};

    /* Design Elements */
    --brand-radius: {$design['border_radius']};
    --brand-radius-lg: {$design['border_radius_lg']};
    --brand-radius-sm: {$design['border_radius_sm']};
    --brand-shadow-sm: {$design['shadow_sm']};
    --brand-shadow: {$design['shadow']};
    --brand-shadow-lg: {$design['shadow_lg']};
}

/* Global Overrides */
body {
    font-family: var(--brand-font-secondary);
    color: var(--brand-text-primary);
    background-color: var(--brand-bg);
}

/* Headings */
h1, h2, h3, h4, h5, h6 {
    font-family: var(--brand-font-primary);
    color: var(--brand-text-primary);
}

/* AdminLTE Theme Overrides */
.main-header .navbar {
    background-color: var(--brand-primary) !important;
    border-bottom: 3px solid var(--brand-primary-dark);
}

.main-sidebar {
    background-color: var(--brand-text-primary);
}

.sidebar-dark-primary .nav-sidebar > .nav-item > .nav-link.active {
    background-color: var(--brand-primary);
    color: white;
}

.brand-link {
    background-color: var(--brand-primary-dark) !important;
    border-bottom: 1px solid var(--brand-primary);
}

.brand-link .brand-text {
    color: white !important;
}

/* Buttons */
.btn-primary {
    background-color: var(--brand-primary);
    border-color: var(--brand-primary);
    border-radius: var(--brand-radius);
}

.btn-primary:hover {
    background-color: var(--brand-primary-dark);
    border-color: var(--brand-primary-dark);
}

.btn-secondary {
    background-color: var(--brand-secondary);
    border-color: var(--brand-secondary);
    border-radius: var(--brand-radius);
}

.btn-accent,
.btn-warning {
    background-color: var(--brand-accent);
    border-color: var(--brand-accent);
    border-radius: var(--brand-radius);
}

/* Cards */
.card {
    border-radius: var(--brand-radius);
    box-shadow: var(--brand-shadow);
    border: none;
}

.card-header {
    background-color: var(--brand-bg-alt);
    border-bottom: 2px solid var(--brand-primary-light);
    font-weight: 600;
}

.card-primary .card-header {
    background-color: var(--brand-primary);
    color: white;
}

/* Links */
a {
    color: var(--brand-primary);
}

a:hover {
    color: var(--brand-primary-dark);
}

/* Badges */
.badge-primary {
    background-color: var(--brand-primary);
}

.badge-success {
    background-color: var(--brand-success);
}

.badge-warning {
    background-color: var(--brand-warning);
}

.badge-danger {
    background-color: var(--brand-danger);
}

.badge-info {
    background-color: var(--brand-info);
}

/* Tailwind Component Overrides */
.bg-primary {
    background-color: var(--brand-primary) !important;
}

.text-primary {
    color: var(--brand-primary) !important;
}

.border-primary {
    border-color: var(--brand-primary) !important;
}

/* Login Page Styles */
.login-page {
    background: var(--brand-primary) !important;
}

.login-card-body {
    border-radius: var(--brand-radius-lg);
    box-shadow: var(--brand-shadow-lg);
}

.login-box-msg {
    color: var(--brand-text-secondary);
}

/* Custom Brand Styles */
.brand-gradient {
    background: linear-gradient(135deg, var(--brand-primary) 0%, var(--brand-primary-dark) 100%);
}

.brand-gradient-accent {
    background: linear-gradient(135deg, var(--brand-accent) 0%, var(--brand-secondary) 100%);
}

.text-brand {
    color: var(--brand-primary);
}

.bg-brand {
    background-color: var(--brand-primary);
}

.hover\:bg-brand-dark:hover {
    background-color: var(--brand-primary-dark);
}

/* Nav Links */
.nav-link {
    border-radius: var(--brand-radius-sm);
}

.sidebar .nav-link:hover {
    background-color: rgba(255, 255, 255, 0.1);
}

/* Forms */
.form-control:focus {
    border-color: var(--brand-primary);
    box-shadow: 0 0 0 0.2rem rgba(37, 99, 235, 0.25);
}

/* Pagination */
.pagination .page-link {
    color: var(--brand-primary);
}

.pagination .page-item.active .page-link {
    background-color: var(--brand-primary);
    border-color: var(--brand-primary);
}

/* Tables */
.table thead th {
    background-color: var(--brand-bg-alt);
    color: var(--brand-text-primary);
    font-weight: 600;
}

/* Alerts */
.alert-primary {
    background-color: var(--brand-primary-light);
    border-color: var(--brand-primary);
    color: var(--brand-primary-dark);
}

/* Modals */
.modal-header {
    background-color: var(--brand-primary);
    color: white;
}

.modal-header .close {
    color: white;
}

/* Progress Bars */
.progress-bar {
    background-color: var(--brand-primary);
}

/* Tooltips */
.tooltip-inner {
    background-color: var(--brand-text-primary);
}

/* Custom Utilities */
.shadow-brand {
    box-shadow: 0 4px 6px -1px rgba(37, 99, 235, 0.1), 0 2px 4px -1px rgba(37, 99, 235, 0.06);
}

.border-brand {
    border-color: var(--brand-primary);
}

/* Responsive Logo */
.brand-logo {
    max-width: 100%;
    height: auto;
}

@media (max-width: 768px) {
    .brand-logo {
        max-width: 150px;
    }
}

/* Print Styles */
@media print {
    .main-header,
    .main-sidebar,
    .content-header {
        display: none !important;
    }

    .content-wrapper {
        margin-left: 0 !important;
        padding: 0 !important;
    }
}

CSS;

        return $css;
    }
}
