import { and, desc, eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { aiTasks, aiUsageTracking } from "@/lib/db/schema/ai-features";
import {
  campaigns,
  contentCalendarItems,
  type CampaignType,
} from "@/lib/db/schema/marketing";
import {
  getMarketingAgentWorkflow,
  marketingAgentDefinitions,
  type MarketingAgentDefinition,
} from "./catalog";
import {
  loadMarketingAgentClientContext,
  serializeClientContext,
} from "./context";
import {
  runJsonMarketingAgent,
  type MarketingAgentCallUsage,
} from "./provider";
import { runMarketingQualityCheck } from "./quality-check";
import type {
  AgentTraceEntry,
  CampaignPlanArtifact,
  ContentCalendarArtifact,
  MarketingAgentRunResult,
  QualityReport,
} from "./types";
import {
  campaignPlanArtifactSchema,
  contentCalendarArtifactSchema,
  marketingAgentRunRequestSchema,
  type MarketingAgentRunRequest,
} from "./validation";

const CAMPAIGN_PLAN_FORMAT = `Return one JSON object with exactly these fields:
title, executiveSummary, objective, targetAudience, keyMessages,
channels [{name, role, budgetPercentage, tactics}],
timeline [{phase, startWeek, endWeek, deliverables}],
kpis [{name, target, measurement}], risks.
Budget percentages must be numbers from 0 to 100.`;

const CONTENT_CALENDAR_FORMAT = `Return one JSON object with exactly these fields:
title, strategySummary, items [{title, platform, contentType, scheduledDate, copy, cta, hashtags}].
scheduledDate must use YYYY-MM-DD. Platform and contentType must use one of the supplied allowed values.`;

interface AgentStageResult<T> {
  value: T;
  trace: AgentTraceEntry;
  usage: MarketingAgentCallUsage;
}

async function runAgentStage<T>({
  clientId,
  agent,
  prompt,
  schema,
}: {
  clientId: string;
  agent: MarketingAgentDefinition;
  prompt: string;
  schema: Parameters<typeof runJsonMarketingAgent<T>>[0]["schema"];
}): Promise<AgentStageResult<T>> {
  const startedAt = new Date().toISOString();
  const result = await runJsonMarketingAgent({
    clientId,
    agent,
    userPrompt: prompt,
    schema,
  });
  const completedAt = new Date().toISOString();

  return {
    value: result.value,
    usage: result.usage,
    trace: {
      agentId: agent.id,
      agentName: agent.name,
      status: "completed",
      summary: agent.purpose,
      startedAt,
      completedAt,
    },
  };
}

function contentForQualityCheck(artifact: CampaignPlanArtifact): string {
  return [
    artifact.executiveSummary,
    artifact.objective,
    artifact.targetAudience,
    ...artifact.keyMessages,
    ...artifact.channels.flatMap((channel) => [
      channel.role,
      ...channel.tactics,
    ]),
  ].join("\n");
}

function calendarForQualityCheck(artifact: ContentCalendarArtifact): string {
  return artifact.items
    .flatMap((item) => [item.title, item.copy, item.cta])
    .join("\n");
}

function inferCampaignType(channels: string[]): CampaignType {
  const normalized = channels.map((channel) => channel.toLowerCase());
  if (normalized.some((channel) => channel.includes("email"))) return "email";
  if (normalized.some((channel) => channel.includes("seo"))) return "seo";
  if (
    normalized.some(
      (channel) =>
        channel.includes("paid") ||
        channel.includes("ppc") ||
        channel.includes("google ads") ||
        channel.includes("meta ads"),
    )
  ) {
    return "ppc";
  }
  if (
    normalized.some(
      (channel) =>
        channel.includes("social") ||
        channel.includes("facebook") ||
        channel.includes("instagram") ||
        channel.includes("linkedin"),
    )
  ) {
    return "social";
  }
  if (normalized.some((channel) => channel.includes("content"))) return "content";
  return "other";
}

async function persistCampaignDraft({
  taskId,
  userId,
  input,
  artifact,
}: {
  taskId: string;
  userId: string | null;
  input: Extract<MarketingAgentRunRequest, { workflowId: "campaign_plan" }>;
  artifact: CampaignPlanArtifact;
}): Promise<MarketingAgentRunResult["createdRecords"]> {
  if (!input.createDrafts) return [];

  const [campaign] = await db
    .insert(campaigns)
    .values({
      clientId: input.clientId,
      name: artifact.title || input.campaignName,
      description: artifact.executiveSummary,
      campaignType: inferCampaignType(
        artifact.channels.map((channel) => channel.name),
      ),
      status: "draft",
      startDate: input.startDate,
      endDate: input.endDate,
      budget: input.budget === undefined ? null : String(input.budget),
      channels: artifact.channels.map((channel) => channel.name),
      createdBy: userId,
      metadata: {
        targetAudience: artifact.targetAudience,
        tags: ["ai-generated", "pending-approval"],
        notes: "Generated by marketing agents. Human approval is required before activation.",
        aiTaskId: taskId,
        agentWorkflow: input.workflowId,
        approvalStatus: "pending_approval",
      },
    })
    .returning({ id: campaigns.id });

  return campaign ? [{ type: "campaign", id: campaign.id }] : [];
}

async function persistCalendarDrafts({
  taskId,
  userId,
  input,
  artifact,
  qualityReport,
}: {
  taskId: string;
  userId: string | null;
  input: Extract<MarketingAgentRunRequest, { workflowId: "content_calendar" }>;
  artifact: ContentCalendarArtifact;
  qualityReport: QualityReport;
}): Promise<MarketingAgentRunResult["createdRecords"]> {
  if (!input.createDrafts || artifact.items.length === 0) return [];

  const rows = await db
    .insert(contentCalendarItems)
    .values(
      artifact.items.map((item) => ({
        clientId: input.clientId,
        title: item.title,
        contentType: item.contentType,
        platform: item.platform,
        scheduledFor: new Date(`${item.scheduledDate}T12:00:00.000Z`),
        status:
          qualityReport.decision === "BLOCKED"
            ? ("needs_revision" as const)
            : ("pending_approval" as const),
        content: item.copy,
        createdBy: userId,
        metadata: {
          hashtags: item.hashtags,
          aiTaskId: taskId,
          agentWorkflow: input.workflowId,
          qualityDecision: qualityReport.decision,
        },
      })),
    )
    .returning({ id: contentCalendarItems.id });

  return rows.map((row) => ({
    type: "content_calendar_item" as const,
    id: row.id,
  }));
}

async function executeCampaignPlan(
  taskId: string,
  userId: string | null,
  input: Extract<MarketingAgentRunRequest, { workflowId: "campaign_plan" }>,
): Promise<{
  result: MarketingAgentRunResult;
  usage: MarketingAgentCallUsage[];
}> {
  const context = await loadMarketingAgentClientContext(input.clientId);
  const clientContext = serializeClientContext(context);
  const strategist = await runAgentStage({
    clientId: input.clientId,
    agent: marketingAgentDefinitions.campaign_strategist,
    schema: campaignPlanArtifactSchema,
    prompt: `${CAMPAIGN_PLAN_FORMAT}\n\nCLIENT_CONTEXT:\n${clientContext}\n\nUSER_INPUT:\n${JSON.stringify(input, null, 2)}`,
  });
  const guardian = await runAgentStage({
    clientId: input.clientId,
    agent: marketingAgentDefinitions.brand_guardian,
    schema: campaignPlanArtifactSchema,
    prompt: `${CAMPAIGN_PLAN_FORMAT}\n\nCLIENT_CONTEXT:\n${clientContext}\n\nUSER_INPUT:\n${JSON.stringify(input, null, 2)}\n\nDRAFT_ARTIFACT:\n${JSON.stringify(strategist.value, null, 2)}`,
  });
  const qualityReport = runMarketingQualityCheck({
    content: contentForQualityCheck(guardian.value),
    voiceAvoid: context.brandGuide.voiceAvoid,
  });
  const createdRecords = await persistCampaignDraft({
    taskId,
    userId,
    input,
    artifact: guardian.value,
  });

  return {
    result: {
      workflowId: input.workflowId,
      approvalStatus: "pending_approval",
      artifact: guardian.value,
      qualityReport,
      agentTrace: [strategist.trace, guardian.trace],
      createdRecords,
    },
    usage: [strategist.usage, guardian.usage],
  };
}

async function executeContentCalendar(
  taskId: string,
  userId: string | null,
  input: Extract<MarketingAgentRunRequest, { workflowId: "content_calendar" }>,
): Promise<{
  result: MarketingAgentRunResult;
  usage: MarketingAgentCallUsage[];
}> {
  const context = await loadMarketingAgentClientContext(input.clientId);
  const clientContext = serializeClientContext(context);
  const creator = await runAgentStage({
    clientId: input.clientId,
    agent: marketingAgentDefinitions.content_creator,
    schema: contentCalendarArtifactSchema,
    prompt: `${CONTENT_CALENDAR_FORMAT}\nCreate exactly ${input.numberOfItems} items using only these platforms: ${input.platforms.join(", ")}.\n\nCLIENT_CONTEXT:\n${clientContext}\n\nUSER_INPUT:\n${JSON.stringify(input, null, 2)}`,
  });
  const guardian = await runAgentStage({
    clientId: input.clientId,
    agent: marketingAgentDefinitions.brand_guardian,
    schema: contentCalendarArtifactSchema,
    prompt: `${CONTENT_CALENDAR_FORMAT}\nPreserve exactly ${input.numberOfItems} items and the requested platforms.\n\nCLIENT_CONTEXT:\n${clientContext}\n\nUSER_INPUT:\n${JSON.stringify(input, null, 2)}\n\nDRAFT_ARTIFACT:\n${JSON.stringify(creator.value, null, 2)}`,
  });
  const qualityReport = runMarketingQualityCheck({
    content: calendarForQualityCheck(guardian.value),
    voiceAvoid: context.brandGuide.voiceAvoid,
  });
  const createdRecords = await persistCalendarDrafts({
    taskId,
    userId,
    input,
    artifact: guardian.value,
    qualityReport,
  });

  return {
    result: {
      workflowId: input.workflowId,
      approvalStatus: "pending_approval",
      artifact: guardian.value,
      qualityReport,
      agentTrace: [creator.trace, guardian.trace],
      createdRecords,
    },
    usage: [creator.usage, guardian.usage],
  };
}

async function executeQualityCheck(
  input: Extract<MarketingAgentRunRequest, { workflowId: "quality_check" }>,
): Promise<{
  result: MarketingAgentRunResult;
  usage: MarketingAgentCallUsage[];
}> {
  const context = await loadMarketingAgentClientContext(input.clientId);
  const startedAt = new Date().toISOString();
  const qualityReport = runMarketingQualityCheck({
    content: input.content,
    evidence: input.evidence,
    voiceAvoid: context.brandGuide.voiceAvoid,
  });
  const completedAt = new Date().toISOString();

  return {
    result: {
      workflowId: input.workflowId,
      approvalStatus: "pending_approval",
      artifact: qualityReport,
      qualityReport,
      agentTrace: [
        {
          agentId: marketingAgentDefinitions.quality_reviewer.id,
          agentName: marketingAgentDefinitions.quality_reviewer.name,
          status: "completed",
          summary: marketingAgentDefinitions.quality_reviewer.purpose,
          startedAt,
          completedAt,
        },
      ],
      createdRecords: [],
    },
    usage: [],
  };
}

async function recordUsage({
  taskId,
  userId,
  clientId,
  workflowId,
  usages,
}: {
  taskId: string;
  userId: string | null;
  clientId: string;
  workflowId: MarketingAgentRunRequest["workflowId"];
  usages: MarketingAgentCallUsage[];
}): Promise<void> {
  if (usages.length === 0) return;

  const total = usages.reduce(
    (summary, usage) => ({
      tokens: summary.tokens + usage.totalTokens,
      promptTokens: summary.promptTokens + usage.promptTokens,
      completionTokens: summary.completionTokens + usage.completionTokens,
      cost: summary.cost + usage.estimatedCost,
    }),
    { tokens: 0, promptTokens: 0, completionTokens: 0, cost: 0 },
  );
  const lastUsage = usages[usages.length - 1];
  const workflow = getMarketingAgentWorkflow(workflowId);

  await db.insert(aiUsageTracking).values({
    userId,
    clientId,
    provider: lastUsage.provider,
    model: lastUsage.model,
    tokensUsed: total.tokens,
    cost: total.cost.toFixed(6),
    requestType: "marketing_agent",
    metadata: {
      taskId,
      workflowId,
      agentIds: workflow.agentIds,
      promptTokens: total.promptTokens,
      completionTokens: total.completionTokens,
    },
  });
}

export async function executeMarketingAgentTask(taskId: string): Promise<void> {
  const [task] = await db
    .select()
    .from(aiTasks)
    .where(and(eq(aiTasks.id, taskId), eq(aiTasks.taskType, "custom")))
    .orderBy(desc(aiTasks.createdAt))
    .limit(1);

  if (!task) throw new Error("Marketing agent task not found.");

  const parsedInput = marketingAgentRunRequestSchema.safeParse(
    task.input.parameters,
  );
  if (!parsedInput.success) {
    throw new Error("Marketing agent task input is invalid.");
  }

  const input = parsedInput.data;
  if (!task.clientId || task.clientId !== input.clientId) {
    throw new Error("Marketing agent task client scope is invalid.");
  }

  await db
    .update(aiTasks)
    .set({
      status: "processing",
      startedAt: new Date(),
      error: null,
      updatedAt: new Date(),
    })
    .where(eq(aiTasks.id, taskId));

  try {
    const execution =
      input.workflowId === "campaign_plan"
        ? await executeCampaignPlan(taskId, task.userId, input)
        : input.workflowId === "content_calendar"
          ? await executeContentCalendar(taskId, task.userId, input)
          : await executeQualityCheck(input);
    const totalTokens = execution.usage.reduce(
      (sum, usage) => sum + usage.totalTokens,
      0,
    );
    const totalCost = execution.usage.reduce(
      (sum, usage) => sum + usage.estimatedCost,
      0,
    );
    const lastUsage = execution.usage[execution.usage.length - 1];

    await recordUsage({
      taskId,
      userId: task.userId,
      clientId: input.clientId,
      workflowId: input.workflowId,
      usages: execution.usage,
    });
    await db
      .update(aiTasks)
      .set({
        output: { result: execution.result },
        status: "completed",
        completedAt: new Date(),
        metadata: {
          ...task.metadata,
          workflowId: input.workflowId,
          approvalStatus: "pending_approval",
          provider: lastUsage?.provider,
          model: lastUsage?.model,
          tokensUsed: totalTokens,
          cost: totalCost,
          agentTrace: execution.result.agentTrace,
        },
        updatedAt: new Date(),
      })
      .where(eq(aiTasks.id, taskId));
  } catch (error) {
    const message =
      error instanceof Error
        ? error.message
        : "The marketing agent run failed unexpectedly.";
    await db
      .update(aiTasks)
      .set({
        status: "failed",
        error: message,
        completedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(aiTasks.id, taskId));
    throw error;
  }
}
