import { ProjectTemplatePhase } from "@/lib/db/schema/project-templates";

/**
 * Comprehensive WordPress Build & Launch Checklist
 *
 * A complete project template covering every phase of a WordPress website build,
 * from initial discovery through post-launch monitoring.
 */
export const wordPressBuildLaunchTemplate = {
  name: "WordPress Build & Launch Checklist",
  description:
    "A comprehensive checklist covering every phase of a WordPress website project — from discovery and planning through development, content, testing, launch, and post-launch monitoring.",
  category: "web_development" as const,
  icon: "Globe",
  color: "#21759b",
  estimatedHours: 120,
  isSystem: true,
  metadata: {
    tags: ["wordpress", "website", "launch", "checklist"],
    version: "1.0",
    source: "kre8iv",
  },
  phases: [
    // ─── Phase 1: Discovery & Planning ───
    {
      name: "Discovery & Planning",
      description: "Gather requirements, define scope, and plan the project.",
      sortOrder: 0,
      tasks: [
        {
          title: "Client Discovery Meeting",
          description: "Conduct kickoff meeting to understand business goals, target audience, and project expectations.",
          priority: "high" as const,
          estimatedHours: 2,
          sortOrder: 0,
          checklist: [
            { title: "Define business goals and objectives", sortOrder: 0 },
            { title: "Identify target audience and user personas", sortOrder: 1 },
            { title: "Gather brand guidelines (logos, colors, fonts)", sortOrder: 2 },
            { title: "Discuss desired features and functionality", sortOrder: 3 },
            { title: "Review competitor websites", sortOrder: 4 },
            { title: "Establish project timeline and milestones", sortOrder: 5 },
          ],
        },
        {
          title: "Define Site Architecture",
          description: "Plan the sitemap, page hierarchy, and navigation structure.",
          priority: "high" as const,
          estimatedHours: 3,
          sortOrder: 1,
          checklist: [
            { title: "Create sitemap with all pages", sortOrder: 0 },
            { title: "Define primary and secondary navigation menus", sortOrder: 1 },
            { title: "Plan URL structure and permalink settings", sortOrder: 2 },
            { title: "Identify content types (pages, posts, CPTs)", sortOrder: 3 },
            { title: "Map out user flows for key actions", sortOrder: 4 },
          ],
        },
        {
          title: "Content Strategy & Inventory",
          description: "Plan content needs and inventory existing assets.",
          priority: "normal" as const,
          estimatedHours: 3,
          sortOrder: 2,
          checklist: [
            { title: "Audit existing content (if redesign)", sortOrder: 0 },
            { title: "Identify content gaps", sortOrder: 1 },
            { title: "Create content outline per page", sortOrder: 2 },
            { title: "Plan blog/news categories and tags", sortOrder: 3 },
            { title: "Define image and media requirements", sortOrder: 4 },
            { title: "Assign content creation responsibilities", sortOrder: 5 },
          ],
        },
        {
          title: "Technology & Plugin Selection",
          description: "Choose the theme, plugins, and hosting environment.",
          priority: "high" as const,
          estimatedHours: 2,
          sortOrder: 3,
          checklist: [
            { title: "Select theme or page builder (custom, starter, etc.)", sortOrder: 0 },
            { title: "Identify required plugins (forms, SEO, security, cache)", sortOrder: 1 },
            { title: "Evaluate hosting requirements", sortOrder: 2 },
            { title: "Plan for staging vs production environments", sortOrder: 3 },
            { title: "Determine third-party integrations (CRM, email, analytics)", sortOrder: 4 },
          ],
        },
      ],
    },

    // ─── Phase 2: Environment Setup ───
    {
      name: "Environment Setup",
      description: "Set up hosting, WordPress installation, and development tools.",
      sortOrder: 1,
      tasks: [
        {
          title: "Hosting & Domain Configuration",
          description: "Provision hosting, configure DNS, and set up SSL.",
          priority: "high" as const,
          estimatedHours: 2,
          sortOrder: 0,
          checklist: [
            { title: "Provision hosting account", sortOrder: 0 },
            { title: "Configure DNS records", sortOrder: 1 },
            { title: "Install and verify SSL certificate", sortOrder: 2 },
            { title: "Set up CDN (if applicable)", sortOrder: 3 },
            { title: "Configure server-level caching", sortOrder: 4 },
            { title: "Set up email service (SMTP)", sortOrder: 5 },
          ],
        },
        {
          title: "WordPress Installation & Core Setup",
          description: "Install WordPress and configure core settings.",
          priority: "high" as const,
          estimatedHours: 1,
          sortOrder: 1,
          checklist: [
            { title: "Install latest WordPress version", sortOrder: 0 },
            { title: "Configure wp-config.php (DB, salts, debug settings)", sortOrder: 1 },
            { title: "Set site title and tagline", sortOrder: 2 },
            { title: "Configure timezone and date format", sortOrder: 3 },
            { title: "Set permalink structure", sortOrder: 4 },
            { title: "Set up search engine visibility (noindex during dev)", sortOrder: 5 },
            { title: "Remove default content (Hello World post, sample page)", sortOrder: 6 },
          ],
        },
        {
          title: "Staging Environment Setup",
          description: "Create a staging site for development and testing.",
          priority: "normal" as const,
          estimatedHours: 1,
          sortOrder: 2,
          checklist: [
            { title: "Set up staging subdomain or environment", sortOrder: 0 },
            { title: "Password-protect staging site", sortOrder: 1 },
            { title: "Block search engine indexing on staging", sortOrder: 2 },
            { title: "Set up deployment workflow (staging → production)", sortOrder: 3 },
          ],
        },
        {
          title: "Version Control & Backup Setup",
          description: "Initialize Git repository and configure backups.",
          priority: "normal" as const,
          estimatedHours: 1,
          sortOrder: 3,
          checklist: [
            { title: "Initialize Git repository", sortOrder: 0 },
            { title: "Create .gitignore for WordPress", sortOrder: 1 },
            { title: "Set up automated backup solution", sortOrder: 2 },
            { title: "Test backup restore process", sortOrder: 3 },
          ],
        },
      ],
    },

    // ─── Phase 3: Theme & Design ───
    {
      name: "Theme & Design",
      description: "Install, configure, and customize the WordPress theme.",
      sortOrder: 2,
      tasks: [
        {
          title: "Theme Installation & Configuration",
          description: "Install the selected theme and apply base configuration.",
          priority: "high" as const,
          estimatedHours: 2,
          sortOrder: 0,
          checklist: [
            { title: "Install and activate selected theme", sortOrder: 0 },
            { title: "Install required child theme (if applicable)", sortOrder: 1 },
            { title: "Configure theme settings and options", sortOrder: 2 },
            { title: "Set up color palette matching brand guidelines", sortOrder: 3 },
            { title: "Configure typography (headings, body, links)", sortOrder: 4 },
            { title: "Set up site logo and favicon", sortOrder: 5 },
          ],
        },
        {
          title: "Homepage Design & Build",
          description: "Design and build the homepage layout.",
          priority: "high" as const,
          estimatedHours: 6,
          sortOrder: 1,
          checklist: [
            { title: "Design hero section", sortOrder: 0 },
            { title: "Build feature/services section", sortOrder: 1 },
            { title: "Add social proof (testimonials, logos, stats)", sortOrder: 2 },
            { title: "Create call-to-action sections", sortOrder: 3 },
            { title: "Build footer layout with links and info", sortOrder: 4 },
            { title: "Ensure mobile responsive design", sortOrder: 5 },
          ],
        },
        {
          title: "Interior Page Templates",
          description: "Build reusable page templates for common layouts.",
          priority: "high" as const,
          estimatedHours: 8,
          sortOrder: 2,
          checklist: [
            { title: "About page template", sortOrder: 0 },
            { title: "Services/Products page template", sortOrder: 1 },
            { title: "Contact page template", sortOrder: 2 },
            { title: "Blog listing template", sortOrder: 3 },
            { title: "Single blog post template", sortOrder: 4 },
            { title: "Landing page template", sortOrder: 5 },
            { title: "404 error page", sortOrder: 6 },
            { title: "Search results page", sortOrder: 7 },
          ],
        },
        {
          title: "Global Components",
          description: "Build shared components used across the site.",
          priority: "normal" as const,
          estimatedHours: 4,
          sortOrder: 3,
          checklist: [
            { title: "Header/navigation (desktop and mobile)", sortOrder: 0 },
            { title: "Footer with columns, links, copyright", sortOrder: 1 },
            { title: "Sidebar widgets (if applicable)", sortOrder: 2 },
            { title: "Breadcrumb navigation", sortOrder: 3 },
            { title: "Social sharing buttons", sortOrder: 4 },
            { title: "Back-to-top button", sortOrder: 5 },
            { title: "Cookie consent banner", sortOrder: 6 },
          ],
        },
      ],
    },

    // ─── Phase 4: Plugin Setup & Configuration ───
    {
      name: "Plugin Setup & Configuration",
      description: "Install and configure all required plugins.",
      sortOrder: 3,
      tasks: [
        {
          title: "Essential Plugins Installation",
          description: "Install and configure core plugins for security, SEO, performance, and forms.",
          priority: "high" as const,
          estimatedHours: 3,
          sortOrder: 0,
          checklist: [
            { title: "SEO plugin (Yoast, RankMath, or SEOPress)", sortOrder: 0 },
            { title: "Security plugin (Wordfence, Sucuri, or iThemes)", sortOrder: 1 },
            { title: "Caching plugin (WP Rocket, W3 Total Cache, or LiteSpeed)", sortOrder: 2 },
            { title: "Forms plugin (Gravity Forms, WPForms, or Contact Form 7)", sortOrder: 3 },
            { title: "Image optimization (ShortPixel, Imagify, or Smush)", sortOrder: 4 },
            { title: "Backup plugin (UpdraftPlus or BlogVault)", sortOrder: 5 },
          ],
        },
        {
          title: "Analytics & Tracking Setup",
          description: "Configure site analytics and conversion tracking.",
          priority: "high" as const,
          estimatedHours: 2,
          sortOrder: 1,
          checklist: [
            { title: "Install Google Analytics / GA4", sortOrder: 0 },
            { title: "Set up Google Tag Manager", sortOrder: 1 },
            { title: "Configure Google Search Console", sortOrder: 2 },
            { title: "Set up conversion tracking (goals, events)", sortOrder: 3 },
            { title: "Install Facebook Pixel (if applicable)", sortOrder: 4 },
            { title: "Configure heatmap tool (Hotjar, Clarity)", sortOrder: 5 },
          ],
        },
        {
          title: "Functionality Plugins",
          description: "Install plugins for additional site features.",
          priority: "normal" as const,
          estimatedHours: 3,
          sortOrder: 2,
          checklist: [
            { title: "WooCommerce (if e-commerce)", sortOrder: 0 },
            { title: "Membership/LMS plugin (if applicable)", sortOrder: 1 },
            { title: "Events calendar (if applicable)", sortOrder: 2 },
            { title: "Multilingual plugin (if applicable)", sortOrder: 3 },
            { title: "Redirection plugin (for 301 redirects)", sortOrder: 4 },
            { title: "Custom post types / ACF (if needed)", sortOrder: 5 },
          ],
        },
        {
          title: "Integration Plugins",
          description: "Set up integrations with third-party services.",
          priority: "normal" as const,
          estimatedHours: 2,
          sortOrder: 3,
          checklist: [
            { title: "Email marketing integration (Mailchimp, ConvertKit, etc.)", sortOrder: 0 },
            { title: "CRM integration (HubSpot, Salesforce, etc.)", sortOrder: 1 },
            { title: "Social media auto-posting", sortOrder: 2 },
            { title: "Live chat / chatbot (if applicable)", sortOrder: 3 },
            { title: "Payment gateway (if applicable)", sortOrder: 4 },
          ],
        },
      ],
    },

    // ─── Phase 5: Content Population ───
    {
      name: "Content Population",
      description: "Create, format, and upload all site content.",
      sortOrder: 4,
      tasks: [
        {
          title: "Page Content Creation",
          description: "Write and format content for all static pages.",
          priority: "high" as const,
          estimatedHours: 10,
          sortOrder: 0,
          checklist: [
            { title: "Homepage content and imagery", sortOrder: 0 },
            { title: "About page content", sortOrder: 1 },
            { title: "Services/Products pages", sortOrder: 2 },
            { title: "Contact page with form and map", sortOrder: 3 },
            { title: "Privacy Policy page", sortOrder: 4 },
            { title: "Terms of Service page", sortOrder: 5 },
            { title: "FAQ page (if applicable)", sortOrder: 6 },
          ],
        },
        {
          title: "Media Library Setup",
          description: "Optimize and upload all images and media files.",
          priority: "normal" as const,
          estimatedHours: 3,
          sortOrder: 1,
          checklist: [
            { title: "Optimize all images for web (compress, resize)", sortOrder: 0 },
            { title: "Add alt text to all images", sortOrder: 1 },
            { title: "Set up image sizes in theme settings", sortOrder: 2 },
            { title: "Upload logos, icons, and brand assets", sortOrder: 3 },
            { title: "Configure lazy loading for images", sortOrder: 4 },
          ],
        },
        {
          title: "Blog / News Content",
          description: "Create initial blog posts and configure the blog.",
          priority: "normal" as const,
          estimatedHours: 4,
          sortOrder: 2,
          checklist: [
            { title: "Create blog categories and tags", sortOrder: 0 },
            { title: "Write and publish initial blog posts (3-5 minimum)", sortOrder: 1 },
            { title: "Set featured images for all posts", sortOrder: 2 },
            { title: "Configure author profiles", sortOrder: 3 },
            { title: "Set up post excerpts", sortOrder: 4 },
          ],
        },
        {
          title: "Menu & Navigation Setup",
          description: "Configure all site navigation menus.",
          priority: "high" as const,
          estimatedHours: 1,
          sortOrder: 3,
          checklist: [
            { title: "Create and assign primary navigation menu", sortOrder: 0 },
            { title: "Create footer navigation menu", sortOrder: 1 },
            { title: "Set up mobile menu", sortOrder: 2 },
            { title: "Configure utility/secondary menus", sortOrder: 3 },
            { title: "Verify all menu links work correctly", sortOrder: 4 },
          ],
        },
      ],
    },

    // ─── Phase 6: SEO & Performance ───
    {
      name: "SEO & Performance",
      description: "Optimize the site for search engines and page speed.",
      sortOrder: 5,
      tasks: [
        {
          title: "On-Page SEO Configuration",
          description: "Configure SEO settings, meta tags, and structured data.",
          priority: "high" as const,
          estimatedHours: 4,
          sortOrder: 0,
          checklist: [
            { title: "Set meta titles and descriptions for all pages", sortOrder: 0 },
            { title: "Configure Open Graph and Twitter Card tags", sortOrder: 1 },
            { title: "Set up XML sitemap and submit to Search Console", sortOrder: 2 },
            { title: "Configure robots.txt", sortOrder: 3 },
            { title: "Add structured data / Schema markup", sortOrder: 4 },
            { title: "Set canonical URLs", sortOrder: 5 },
            { title: "Verify heading hierarchy (H1-H6) on all pages", sortOrder: 6 },
            { title: "Set up breadcrumb schema", sortOrder: 7 },
          ],
        },
        {
          title: "Performance Optimization",
          description: "Optimize site speed and Core Web Vitals.",
          priority: "high" as const,
          estimatedHours: 4,
          sortOrder: 1,
          checklist: [
            { title: "Enable page caching", sortOrder: 0 },
            { title: "Enable browser caching", sortOrder: 1 },
            { title: "Minify CSS and JavaScript", sortOrder: 2 },
            { title: "Defer non-critical JavaScript", sortOrder: 3 },
            { title: "Optimize database (clean transients, revisions)", sortOrder: 4 },
            { title: "Enable GZIP compression", sortOrder: 5 },
            { title: "Optimize web fonts loading", sortOrder: 6 },
            { title: "Test with Google PageSpeed Insights (target 90+)", sortOrder: 7 },
            { title: "Test Core Web Vitals (LCP, FID, CLS)", sortOrder: 8 },
          ],
        },
        {
          title: "301 Redirects (if migration)",
          description: "Set up redirects from old URLs to new URLs.",
          priority: "normal" as const,
          estimatedHours: 2,
          sortOrder: 2,
          checklist: [
            { title: "Map old URLs to new URLs", sortOrder: 0 },
            { title: "Set up 301 redirects", sortOrder: 1 },
            { title: "Test all redirects", sortOrder: 2 },
            { title: "Submit updated sitemap to Search Console", sortOrder: 3 },
          ],
        },
      ],
    },

    // ─── Phase 7: Security Hardening ───
    {
      name: "Security Hardening",
      description: "Secure the WordPress installation against common threats.",
      sortOrder: 6,
      tasks: [
        {
          title: "WordPress Security Configuration",
          description: "Harden WordPress core security settings.",
          priority: "high" as const,
          estimatedHours: 3,
          sortOrder: 0,
          checklist: [
            { title: "Change default admin username", sortOrder: 0 },
            { title: "Set strong passwords for all users", sortOrder: 1 },
            { title: "Enable two-factor authentication", sortOrder: 2 },
            { title: "Limit login attempts", sortOrder: 3 },
            { title: "Change default wp-login URL", sortOrder: 4 },
            { title: "Disable XML-RPC (if not needed)", sortOrder: 5 },
            { title: "Disable file editing in wp-admin", sortOrder: 6 },
            { title: "Set correct file permissions (644/755)", sortOrder: 7 },
            { title: "Hide WordPress version number", sortOrder: 8 },
            { title: "Disable directory browsing", sortOrder: 9 },
          ],
        },
        {
          title: "Firewall & Monitoring",
          description: "Set up web application firewall and security monitoring.",
          priority: "high" as const,
          estimatedHours: 1,
          sortOrder: 1,
          checklist: [
            { title: "Configure web application firewall (WAF)", sortOrder: 0 },
            { title: "Set up malware scanning", sortOrder: 1 },
            { title: "Enable security email alerts", sortOrder: 2 },
            { title: "Set up uptime monitoring", sortOrder: 3 },
            { title: "Configure security headers (CSP, X-Frame, HSTS)", sortOrder: 4 },
          ],
        },
        {
          title: "SSL & Data Protection",
          description: "Ensure all data transmission is encrypted.",
          priority: "high" as const,
          estimatedHours: 1,
          sortOrder: 2,
          checklist: [
            { title: "Verify SSL is active on all pages", sortOrder: 0 },
            { title: "Force HTTPS redirect", sortOrder: 1 },
            { title: "Check for mixed content warnings", sortOrder: 2 },
            { title: "Configure secure cookies", sortOrder: 3 },
          ],
        },
      ],
    },

    // ─── Phase 8: Testing & QA ───
    {
      name: "Testing & QA",
      description: "Thoroughly test the site across devices, browsers, and scenarios.",
      sortOrder: 7,
      tasks: [
        {
          title: "Cross-Browser Testing",
          description: "Test site functionality across all major browsers.",
          priority: "high" as const,
          estimatedHours: 3,
          sortOrder: 0,
          checklist: [
            { title: "Chrome (latest)", sortOrder: 0 },
            { title: "Firefox (latest)", sortOrder: 1 },
            { title: "Safari (latest)", sortOrder: 2 },
            { title: "Edge (latest)", sortOrder: 3 },
            { title: "iOS Safari (iPhone and iPad)", sortOrder: 4 },
            { title: "Android Chrome", sortOrder: 5 },
          ],
        },
        {
          title: "Responsive Design Testing",
          description: "Verify the site works on all screen sizes.",
          priority: "high" as const,
          estimatedHours: 2,
          sortOrder: 1,
          checklist: [
            { title: "Desktop (1920px, 1440px, 1280px)", sortOrder: 0 },
            { title: "Tablet landscape (1024px)", sortOrder: 1 },
            { title: "Tablet portrait (768px)", sortOrder: 2 },
            { title: "Mobile large (425px)", sortOrder: 3 },
            { title: "Mobile small (375px, 320px)", sortOrder: 4 },
            { title: "Test hamburger/mobile menu", sortOrder: 5 },
          ],
        },
        {
          title: "Functionality Testing",
          description: "Test all interactive elements and functionality.",
          priority: "high" as const,
          estimatedHours: 3,
          sortOrder: 2,
          checklist: [
            { title: "All forms submit correctly and send notifications", sortOrder: 0 },
            { title: "All internal links work (no 404s)", sortOrder: 1 },
            { title: "All external links open in new tab", sortOrder: 2 },
            { title: "Search functionality works", sortOrder: 3 },
            { title: "Social media links are correct", sortOrder: 4 },
            { title: "Email links (mailto:) work", sortOrder: 5 },
            { title: "Phone links (tel:) work on mobile", sortOrder: 6 },
            { title: "File downloads work", sortOrder: 7 },
            { title: "Video/audio embeds play correctly", sortOrder: 8 },
            { title: "Maps display and function correctly", sortOrder: 9 },
          ],
        },
        {
          title: "Accessibility Testing",
          description: "Ensure the site meets WCAG accessibility standards.",
          priority: "normal" as const,
          estimatedHours: 2,
          sortOrder: 3,
          checklist: [
            { title: "Run WAVE or axe accessibility audit", sortOrder: 0 },
            { title: "Verify keyboard navigation works", sortOrder: 1 },
            { title: "Check color contrast ratios (WCAG AA)", sortOrder: 2 },
            { title: "Verify all images have alt text", sortOrder: 3 },
            { title: "Check form labels and ARIA attributes", sortOrder: 4 },
            { title: "Test with screen reader (VoiceOver/NVDA)", sortOrder: 5 },
            { title: "Verify focus indicators are visible", sortOrder: 6 },
            { title: "Check skip navigation link", sortOrder: 7 },
          ],
        },
        {
          title: "Content Review",
          description: "Proofread and review all content for accuracy.",
          priority: "normal" as const,
          estimatedHours: 2,
          sortOrder: 4,
          checklist: [
            { title: "Spell check all pages", sortOrder: 0 },
            { title: "Grammar review", sortOrder: 1 },
            { title: "Verify business info (address, phone, email)", sortOrder: 2 },
            { title: "Check all images display correctly", sortOrder: 3 },
            { title: "Verify copyright year", sortOrder: 4 },
            { title: "Review legal pages (privacy, terms)", sortOrder: 5 },
          ],
        },
      ],
    },

    // ─── Phase 9: Pre-Launch Checklist ───
    {
      name: "Pre-Launch Checklist",
      description: "Final checks before going live.",
      sortOrder: 8,
      tasks: [
        {
          title: "Final Technical Checks",
          description: "Last round of technical verification before launch.",
          priority: "urgent" as const,
          estimatedHours: 2,
          sortOrder: 0,
          checklist: [
            { title: "Remove 'noindex' and allow search engine indexing", sortOrder: 0 },
            { title: "Remove staging password protection", sortOrder: 1 },
            { title: "Verify production environment settings", sortOrder: 2 },
            { title: "Check wp-config.php debug mode is OFF", sortOrder: 3 },
            { title: "Verify cron jobs are configured", sortOrder: 4 },
            { title: "Test email delivery from production", sortOrder: 5 },
            { title: "Verify all API keys are production keys", sortOrder: 6 },
            { title: "Check PHP error logging is configured", sortOrder: 7 },
          ],
        },
        {
          title: "Backup & Recovery Preparation",
          description: "Ensure backup systems are in place before launch.",
          priority: "high" as const,
          estimatedHours: 1,
          sortOrder: 1,
          checklist: [
            { title: "Create full site backup (files + database)", sortOrder: 0 },
            { title: "Verify backup can be restored", sortOrder: 1 },
            { title: "Document rollback procedure", sortOrder: 2 },
            { title: "Confirm automated backups are scheduled", sortOrder: 3 },
          ],
        },
        {
          title: "Client Approval",
          description: "Get final sign-off from the client before launch.",
          priority: "urgent" as const,
          estimatedHours: 1,
          sortOrder: 2,
          checklist: [
            { title: "Present staging site for final review", sortOrder: 0 },
            { title: "Walk through all pages with client", sortOrder: 1 },
            { title: "Document any last-minute change requests", sortOrder: 2 },
            { title: "Get written approval to launch", sortOrder: 3 },
          ],
        },
      ],
    },

    // ─── Phase 10: Launch ───
    {
      name: "Launch",
      description: "Deploy the site to production and verify everything works.",
      sortOrder: 9,
      tasks: [
        {
          title: "Deployment",
          description: "Push the site live and verify the deployment.",
          priority: "urgent" as const,
          estimatedHours: 2,
          sortOrder: 0,
          checklist: [
            { title: "Deploy code to production server", sortOrder: 0 },
            { title: "Point domain DNS to production server", sortOrder: 1 },
            { title: "Verify SSL certificate on production", sortOrder: 2 },
            { title: "Update WordPress site URL settings", sortOrder: 3 },
            { title: "Clear all caches (server, CDN, WordPress)", sortOrder: 4 },
            { title: "Verify all pages load on live domain", sortOrder: 5 },
          ],
        },
        {
          title: "Post-Deploy Verification",
          description: "Run smoke tests on the live site.",
          priority: "urgent" as const,
          estimatedHours: 1,
          sortOrder: 1,
          checklist: [
            { title: "Test homepage loads correctly", sortOrder: 0 },
            { title: "Test all major pages", sortOrder: 1 },
            { title: "Test contact form submission", sortOrder: 2 },
            { title: "Test search functionality", sortOrder: 3 },
            { title: "Verify analytics tracking is active", sortOrder: 4 },
            { title: "Check Google Search Console for errors", sortOrder: 5 },
            { title: "Run PageSpeed test on live site", sortOrder: 6 },
            { title: "Verify sitemap is accessible", sortOrder: 7 },
          ],
        },
      ],
    },

    // ─── Phase 11: Post-Launch ───
    {
      name: "Post-Launch",
      description: "Monitor, maintain, and hand off the site after launch.",
      sortOrder: 10,
      tasks: [
        {
          title: "Monitoring Setup",
          description: "Set up ongoing monitoring and alerts.",
          priority: "high" as const,
          estimatedHours: 1,
          sortOrder: 0,
          checklist: [
            { title: "Set up uptime monitoring (Pingdom, UptimeRobot)", sortOrder: 0 },
            { title: "Configure error alert notifications", sortOrder: 1 },
            { title: "Monitor Google Search Console for crawl errors", sortOrder: 2 },
            { title: "Set up performance monitoring baseline", sortOrder: 3 },
            { title: "Monitor security plugin alerts", sortOrder: 4 },
          ],
        },
        {
          title: "Client Training & Handoff",
          description: "Train the client on managing their WordPress site.",
          priority: "high" as const,
          estimatedHours: 2,
          sortOrder: 1,
          checklist: [
            { title: "Create admin user accounts for client team", sortOrder: 0 },
            { title: "Train on content editing (pages, posts, media)", sortOrder: 1 },
            { title: "Train on form management", sortOrder: 2 },
            { title: "Provide documentation / user guide", sortOrder: 3 },
            { title: "Record training video (optional)", sortOrder: 4 },
            { title: "Share all login credentials securely", sortOrder: 5 },
          ],
        },
        {
          title: "Maintenance Plan Setup",
          description: "Establish ongoing maintenance and support plan.",
          priority: "normal" as const,
          estimatedHours: 1,
          sortOrder: 2,
          checklist: [
            { title: "Define maintenance plan scope", sortOrder: 0 },
            { title: "Schedule WordPress core updates", sortOrder: 1 },
            { title: "Schedule plugin and theme updates", sortOrder: 2 },
            { title: "Set up monthly performance review", sortOrder: 3 },
            { title: "Define support SLA and response times", sortOrder: 4 },
            { title: "Set up monthly analytics reporting", sortOrder: 5 },
          ],
        },
        {
          title: "SEO Submission & Social Profiles",
          description: "Submit the site to search engines and update online profiles.",
          priority: "normal" as const,
          estimatedHours: 2,
          sortOrder: 3,
          checklist: [
            { title: "Submit sitemap to Google Search Console", sortOrder: 0 },
            { title: "Submit sitemap to Bing Webmaster Tools", sortOrder: 1 },
            { title: "Update Google Business Profile with new URL", sortOrder: 2 },
            { title: "Update social media profiles with new URL", sortOrder: 3 },
            { title: "Set up Google Alerts for brand name", sortOrder: 4 },
            { title: "Submit site to relevant directories", sortOrder: 5 },
          ],
        },
      ],
    },
  ] satisfies ProjectTemplatePhase[],
};
